### ISSUE TITLE
no jala

### ISSUE THREAD

**Issue by AdrianMCC** [Pablo73MCC/TaskCollect#4]
![image](https://github.com/Pablo73MCC/TaskCollect/assets/124717650/fa75251a-0e0b-4bbe-910d-a1f66f07bb32)

**Comment by Pablo73MCC** [comment]
![Sin título](https://github.com/Pablo73MCC/TaskCollect/assets/124717763/78992a8e-4228-4685-b1dc-79f92e00edf8)
